[2024-11-02T13:42:57.972+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T13:42:58.015+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tem.bash_task2 manual__2024-11-02T13:42:53.599634+00:00 [queued]>
[2024-11-02T13:42:58.034+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tem.bash_task2 manual__2024-11-02T13:42:53.599634+00:00 [queued]>
[2024-11-02T13:42:58.035+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-02T13:42:58.068+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): bash_task2> on 2024-11-02 13:42:53.599634+00:00
[2024-11-02T13:42:58.077+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=669) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T13:42:58.079+0000] {standard_task_runner.py:72} INFO - Started process 670 to run task
[2024-11-02T13:42:58.080+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tem', 'bash_task2', 'manual__2024-11-02T13:42:53.599634+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/templatin/template.py', '--cfg-path', '/tmp/tmpyg4tdpzh']
[2024-11-02T13:42:58.082+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask bash_task2
[2024-11-02T13:42:58.146+0000] {task_command.py:467} INFO - Running <TaskInstance: tem.bash_task2 manual__2024-11-02T13:42:53.599634+00:00 [running]> on host fe3e688f2b29
[2024-11-02T13:42:58.320+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ade' AIRFLOW_CTX_DAG_ID='tem' AIRFLOW_CTX_TASK_ID='bash_task2' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T13:42:53.599634+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T13:42:53.599634+00:00'
[2024-11-02T13:42:58.321+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T13:42:58.342+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-02T13:42:58.343+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "12"']
[2024-11-02T13:42:58.357+0000] {subprocess.py:86} INFO - Output:
[2024-11-02T13:42:58.359+0000] {subprocess.py:93} INFO - 12
[2024-11-02T13:42:58.359+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-02T13:42:58.393+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T13:42:58.394+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tem, task_id=bash_task2, run_id=manual__2024-11-02T13:42:53.599634+00:00, execution_date=20241102T134253, start_date=20241102T134258, end_date=20241102T134258
[2024-11-02T13:42:58.455+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T13:42:58.508+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-02T13:42:58.533+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
