[2024-11-02T13:33:53.048+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T13:33:53.076+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tem.bash_task3 manual__2024-11-02T13:33:46.920704+00:00 [queued]>
[2024-11-02T13:33:53.093+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tem.bash_task3 manual__2024-11-02T13:33:46.920704+00:00 [queued]>
[2024-11-02T13:33:53.094+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-02T13:33:53.118+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): bash_task3> on 2024-11-02 13:33:46.920704+00:00
[2024-11-02T13:33:53.126+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=524) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T13:33:53.128+0000] {standard_task_runner.py:72} INFO - Started process 525 to run task
[2024-11-02T13:33:53.129+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tem', 'bash_task3', 'manual__2024-11-02T13:33:46.920704+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/templatin/template.py', '--cfg-path', '/tmp/tmpdzjpf98k']
[2024-11-02T13:33:53.130+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask bash_task3
[2024-11-02T13:33:53.199+0000] {task_command.py:467} INFO - Running <TaskInstance: tem.bash_task3 manual__2024-11-02T13:33:46.920704+00:00 [running]> on host fe3e688f2b29
[2024-11-02T13:33:53.332+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ade' AIRFLOW_CTX_DAG_ID='tem' AIRFLOW_CTX_TASK_ID='bash_task3' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T13:33:46.920704+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T13:33:46.920704+00:00'
[2024-11-02T13:33:53.334+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T13:33:53.359+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-02T13:33:53.361+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "2024-11-02"']
[2024-11-02T13:33:53.375+0000] {subprocess.py:86} INFO - Output:
[2024-11-02T13:33:53.377+0000] {subprocess.py:93} INFO - 2024-11-02
[2024-11-02T13:33:53.378+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-02T13:33:53.423+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T13:33:53.424+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tem, task_id=bash_task3, run_id=manual__2024-11-02T13:33:46.920704+00:00, execution_date=20241102T133346, start_date=20241102T133353, end_date=20241102T133353
[2024-11-02T13:33:53.464+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T13:33:53.486+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-02T13:33:53.491+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
