[0m22:03:35.926945 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba71bbc370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba726cb460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba70252160>]}


============================== 22:03:35.952533 | 65de5295-e321-47fc-ac53-a94543c97caf ==============================
[0m22:03:35.952533 [info ] [MainThread]: Running with dbt=1.8.7
[0m22:03:35.954335 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/adewunmi/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m22:03:36.292504 [debug] [MainThread]: Starter project path: /mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/capstone_dbt/lib/python3.8/site-packages/dbt/include/starter_project
[0m22:03:37.323217 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:03:37.370682 [info ] [MainThread]: Setting up your profile.
[0m22:04:32.398156 [info ] [MainThread]: Profile dbt_project written to /home/adewunmi/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:04:32.403378 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 56.786385, "process_user_time": 2.793449, "process_kernel_time": 1.306935, "process_mem_max_rss": "85980", "process_in_blocks": "14416", "process_out_blocks": "8"}
[0m22:04:32.404730 [debug] [MainThread]: Command `dbt init` succeeded at 22:04:32.404458 after 56.79 seconds
[0m22:04:32.405556 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba71bbc370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba71d1ac10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba702527c0>]}
[0m22:04:32.406620 [debug] [MainThread]: Flushing usage events
[0m22:07:32.120762 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34aa495370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34a90769a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34aafa4460>]}


============================== 22:07:32.133335 | 806c3907-bc5d-4fa3-abf7-4a7fff4ff7ee ==============================
[0m22:07:32.133335 [info ] [MainThread]: Running with dbt=1.8.7
[0m22:07:32.134792 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/adewunmi/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:07:32.136402 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:07:32.140727 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.1066537, "process_user_time": 2.488337, "process_kernel_time": 1.059847, "process_mem_max_rss": "80088", "process_in_blocks": "5864", "command_success": false, "process_out_blocks": "0"}
[0m22:07:32.142125 [debug] [MainThread]: Command `dbt test` failed at 22:07:32.141940 after 0.11 seconds
[0m22:07:32.142956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34aa495370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34a8b2a880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34a8ca6a00>]}
[0m22:07:32.143789 [debug] [MainThread]: Flushing usage events
[0m00:50:50.623658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd553f2b460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd553341700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd55311ca00>]}


============================== 00:50:50.760662 | 551877df-8942-49f2-a1ed-112a9586ef4c ==============================
[0m00:50:50.760662 [info ] [MainThread]: Running with dbt=1.8.7
[0m00:50:50.762654 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/adewunmi/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:51:22.896053 [error] [MainThread]: Encountered an error:

[0m00:51:22.973792 [error] [MainThread]: Traceback (most recent call last):
  File "/mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/capstone_dbt/lib/python3.8/site-packages/dbt/cli/requires.py", line 128, in wrapper
    result, success = func(*args, **kwargs)
  File "/mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/capstone_dbt/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/capstone_dbt/lib/python3.8/site-packages/dbt/cli/main.py", line 464, in init
    results = task.run()
  File "/mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/capstone_dbt/lib/python3.8/site-packages/dbt/task/init.py", line 318, in run
    project_name = self.get_valid_project_name()
  File "/mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/capstone_dbt/lib/python3.8/site-packages/dbt/task/init.py", line 272, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "/mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/capstone_dbt/lib/python3.8/site-packages/click/termui.py", line 159, in prompt
    value = prompt_func(prompt)
  File "/mnt/c/Users/Lenovo-T440p/airflow/dbt_postgres/capstone_dbt/lib/python3.8/site-packages/click/termui.py", line 142, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m00:51:22.982716 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 32.522404, "process_user_time": 3.123213, "process_kernel_time": 1.834101, "process_mem_max_rss": "89440", "process_in_blocks": "8528", "command_success": false, "process_out_blocks": "0"}
[0m00:51:22.986607 [debug] [MainThread]: Command `dbt init` failed at 00:51:22.986151 after 32.53 seconds
[0m00:51:22.987696 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd553f2b460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd5530e11f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd552842940>]}
[0m00:51:22.988592 [debug] [MainThread]: Flushing usage events
