[2024-11-19T19:49:33.023+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T19:49:33.048+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone.load_to_database manual__2024-11-19T19:26:50.048854+00:00 [queued]>
[2024-11-19T19:49:33.060+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone.load_to_database manual__2024-11-19T19:26:50.048854+00:00 [queued]>
[2024-11-19T19:49:33.061+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 5
[2024-11-19T19:49:33.083+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_database> on 2024-11-19 19:26:50.048854+00:00
[2024-11-19T19:49:33.092+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2429) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-19T19:49:33.095+0000] {standard_task_runner.py:72} INFO - Started process 2431 to run task
[2024-11-19T19:49:33.095+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'capstone', 'load_to_database', 'manual__2024-11-19T19:26:50.048854+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/capstone_***/country.py', '--cfg-path', '/tmp/tmpduzb3gd6']
[2024-11-19T19:49:33.100+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask load_to_database
[2024-11-19T19:49:33.161+0000] {task_command.py:467} INFO - Running <TaskInstance: capstone.load_to_database manual__2024-11-19T19:26:50.048854+00:00 [running]> on host ea8ac57aed30
[2024-11-19T19:49:33.309+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='adewunmi' AIRFLOW_CTX_DAG_ID='capstone' AIRFLOW_CTX_TASK_ID='load_to_database' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T19:26:50.048854+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T19:26:50.048854+00:00'
[2024-11-19T19:49:33.312+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T19:49:33.336+0000] {cap.py:466} INFO - Starting the database load process.
[2024-11-19T19:49:33.336+0000] {cap.py:431} INFO - Starting the column renaming process.
[2024-11-19T19:49:33.337+0000] {cap.py:383} INFO - Starting table transformation process.
[2024-11-19T19:49:33.337+0000] {cap.py:328} INFO - Starting the table joining process.
[2024-11-19T19:49:33.338+0000] {cap.py:137} INFO - Starting column selection process.
[2024-11-19T19:49:36.894+0000] {cap.py:118} INFO - Successfully read Parquet file from S3.
[2024-11-19T19:49:36.896+0000] {cap.py:147} INFO - Data loaded successfully from S3.
[2024-11-19T19:49:36.900+0000] {cap.py:159} INFO - Column selection completed successfully.
[2024-11-19T19:49:36.904+0000] {cap.py:176} INFO - Starting currency extraction process.
[2024-11-19T19:49:41.178+0000] {cap.py:118} INFO - Successfully read Parquet file from S3.
[2024-11-19T19:49:41.180+0000] {cap.py:186} INFO - Data loaded successfully from S3.
[2024-11-19T19:49:41.180+0000] {cap.py:194} INFO - Filtering currency symbol columns and joining with country names.
[2024-11-19T19:49:41.219+0000] {cap.py:198} INFO - Melting the data to extract currency codes and symbols.
[2024-11-19T19:49:41.265+0000] {cap.py:202} INFO - Removing rows with null currency symbols.
[2024-11-19T19:49:41.315+0000] {cap.py:206} INFO - Cleaning up currency codes.
[2024-11-19T19:49:41.318+0000] {cap.py:210} INFO - Grouping by country and aggregating currency symbols and codes.
[2024-11-19T19:49:41.398+0000] {cap.py:216} INFO - Currency extraction completed successfully.
[2024-11-19T19:49:41.404+0000] {cap.py:343} INFO - Currency code and symbol extracted successfully.
[2024-11-19T19:49:41.405+0000] {cap.py:232} INFO - Starting currency name extraction process.
[2024-11-19T19:51:49.987+0000] {cap.py:118} INFO - Successfully read Parquet file from S3.
[2024-11-19T19:51:49.989+0000] {cap.py:242} INFO - Data loaded successfully from S3.
[2024-11-19T19:51:49.989+0000] {cap.py:245} INFO - Filtering country names and currency name columns.
[2024-11-19T19:51:50.027+0000] {cap.py:249} INFO - Melting data to extract currency names.
[2024-11-19T19:51:50.057+0000] {cap.py:253} INFO - Removing rows with null currency names.
[2024-11-19T19:51:50.097+0000] {cap.py:260} INFO - Grouping by country and aggregating currency names.
[2024-11-19T19:51:50.141+0000] {cap.py:263} INFO - Currency name extraction completed successfully.
[2024-11-19T19:51:50.147+0000] {cap.py:350} INFO - Currency name extracted successfully.
[2024-11-19T19:51:50.149+0000] {cap.py:281} INFO - Starting language extraction process.
[2024-11-19T19:54:42.468+0000] {cap.py:118} INFO - Successfully read Parquet file from S3.
[2024-11-19T19:54:42.472+0000] {cap.py:291} INFO - Data loaded successfully from S3.
[2024-11-19T19:54:42.473+0000] {cap.py:294} INFO - Filtering country names and language columns.
[2024-11-19T19:54:42.632+0000] {cap.py:298} INFO - Melting data to extract languages.
[2024-11-19T19:54:42.742+0000] {cap.py:302} INFO - Removing rows with null language values.
[2024-11-19T19:54:42.823+0000] {cap.py:309} INFO - Grouping by country and aggregating languages.
[2024-11-19T19:54:42.875+0000] {cap.py:312} INFO - Language extraction completed successfully.
[2024-11-19T19:54:42.881+0000] {cap.py:357} INFO - Languages extracted successfully.
[2024-11-19T19:54:42.882+0000] {cap.py:360} INFO - Joining tables.
[2024-11-19T19:54:42.903+0000] {cap.py:365} INFO - Tables joined successfully.
[2024-11-19T19:54:42.904+0000] {cap.py:392} INFO - Data joined successfully for transformation.
[2024-11-19T19:54:42.922+0000] {cap.py:403} INFO - Column continents transformed successfully.
[2024-11-19T19:54:42.944+0000] {cap.py:403} INFO - Column idd.suffixes transformed successfully.
[2024-11-19T19:54:42.968+0000] {cap.py:403} INFO - Column capital transformed successfully.
[2024-11-19T19:54:42.971+0000] {cap.py:410} INFO - 'country_code' column created successfully.
[2024-11-19T19:54:42.973+0000] {cap.py:416} INFO - Unnecessary columns dropped successfully.
[2024-11-19T19:54:42.975+0000] {cap.py:444} INFO - Column renaming completed successfully.
[2024-11-19T19:54:42.980+0000] {cap.py:473} INFO - DataFrame validation successful. Proceeding to database connection.
[2024-11-19T19:54:42.982+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/capstone_airflow/function/cap.py", line 476, in load_to_database
    postgres_hook = PostgresHook(postgres_conn_id='rds_connect')
                    ^^^^^^^^^^^^
NameError: name 'PostgresHook' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/capstone_airflow/function/cap.py", line 496, in load_to_database
    raise Exception(f"Error during database load process: {str(e)}")
Exception: Error during database load process: name 'PostgresHook' is not defined
[2024-11-19T19:54:43.029+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=capstone, task_id=load_to_database, run_id=manual__2024-11-19T19:26:50.048854+00:00, execution_date=20241119T192650, start_date=20241119T194933, end_date=20241119T195443
[2024-11-19T19:54:43.075+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T19:54:43.077+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 71 for task load_to_database (Error during database load process: name 'PostgresHook' is not defined; 2431)
Traceback (most recent call last):
  File "/opt/airflow/dags/capstone_airflow/function/cap.py", line 476, in load_to_database
    postgres_hook = PostgresHook(postgres_conn_id='rds_connect')
                    ^^^^^^^^^^^^
NameError: name 'PostgresHook' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/capstone_airflow/function/cap.py", line 496, in load_to_database
    raise Exception(f"Error during database load process: {str(e)}")
Exception: Error during database load process: name 'PostgresHook' is not defined
[2024-11-19T19:54:43.170+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-19T19:54:43.221+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-19T19:54:43.238+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
