[2024-10-19T18:52:49.092+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T18:52:49.116+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wiki_pageviews_dag.creating_postgres_table manual__2024-10-19T18:07:23.965242+00:00 [queued]>
[2024-10-19T18:52:49.130+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wiki_pageviews_dag.creating_postgres_table manual__2024-10-19T18:07:23.965242+00:00 [queued]>
[2024-10-19T18:52:49.131+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-19T18:52:49.157+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): creating_postgres_table> on 2024-10-19 18:07:23.965242+00:00
[2024-10-19T18:52:49.171+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2666) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T18:52:49.177+0000] {standard_task_runner.py:72} INFO - Started process 2668 to run task
[2024-10-19T18:52:49.177+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'wiki_pageviews_dag', 'creating_postgres_table', 'manual__2024-10-19T18:07:23.965242+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/prod.py', '--cfg-path', '/tmp/tmpsg1x0_6z']
[2024-10-19T18:52:49.185+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask creating_postgres_table
[2024-10-19T18:52:49.285+0000] {task_command.py:467} INFO - Running <TaskInstance: wiki_pageviews_dag.creating_postgres_table manual__2024-10-19T18:07:23.965242+00:00 [running]> on host 533638d20908
[2024-10-19T18:52:49.485+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Adewunmi' AIRFLOW_CTX_DAG_ID='wiki_pageviews_dag' AIRFLOW_CTX_TASK_ID='creating_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T18:07:23.965242+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T18:07:23.965242+00:00'
[2024-10-19T18:52:49.487+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T18:52:49.521+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/function_csv/test.py", line 4, in create_postgres_table
    pg_hook = PostgresHook(postgres_conn_id='post_s3')
              ^^^^^^^^^^^^
NameError: name 'PostgresHook' is not defined
[2024-10-19T18:52:49.563+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=wiki_pageviews_dag, task_id=creating_postgres_table, run_id=manual__2024-10-19T18:07:23.965242+00:00, execution_date=20241019T180723, start_date=20241019T185249, end_date=20241019T185249
[2024-10-19T18:52:49.603+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T18:52:49.605+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task creating_postgres_table (name 'PostgresHook' is not defined; 2668)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/function_csv/test.py", line 4, in create_postgres_table
    pg_hook = PostgresHook(postgres_conn_id='post_s3')
              ^^^^^^^^^^^^
NameError: name 'PostgresHook' is not defined
[2024-10-19T18:52:49.680+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-19T18:52:49.735+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-19T18:52:49.748+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
